// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwB-JbOFu2iUzFQAB1eBUD8zMyfhbY3jw',
    appId: '1:887176133094:web:cdaaa1e10a0e57aa683e27',
    messagingSenderId: '887176133094',
    projectId: 'ebook-c1668',
    authDomain: 'ebook-c1668.firebaseapp.com',
    storageBucket: 'ebook-c1668.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_tvN-UpL-s9Z9OYnEfnTo5S12aYMlT7Y',
    appId: '1:887176133094:android:5436cb8b1a2e95bc683e27',
    messagingSenderId: '887176133094',
    projectId: 'ebook-c1668',
    storageBucket: 'ebook-c1668.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaLV4DmyS1MQ7DBkQupgJWSnSiuZn4DO0',
    appId: '1:887176133094:ios:2f145744cb493711683e27',
    messagingSenderId: '887176133094',
    projectId: 'ebook-c1668',
    storageBucket: 'ebook-c1668.appspot.com',
    androidClientId: '887176133094-6n8324l3cvq5uml2ptg34bocijrurupu.apps.googleusercontent.com',
    iosClientId: '887176133094-0b9rc4cjeo1ruh0a13v2d51glc6gk421.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaLV4DmyS1MQ7DBkQupgJWSnSiuZn4DO0',
    appId: '1:887176133094:ios:2f145744cb493711683e27',
    messagingSenderId: '887176133094',
    projectId: 'ebook-c1668',
    storageBucket: 'ebook-c1668.appspot.com',
    androidClientId: '887176133094-6n8324l3cvq5uml2ptg34bocijrurupu.apps.googleusercontent.com',
    iosClientId: '887176133094-0b9rc4cjeo1ruh0a13v2d51glc6gk421.apps.googleusercontent.com',
    iosBundleId: 'com.example.eBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwB-JbOFu2iUzFQAB1eBUD8zMyfhbY3jw',
    appId: '1:887176133094:web:7af976ccae4de250683e27',
    messagingSenderId: '887176133094',
    projectId: 'ebook-c1668',
    authDomain: 'ebook-c1668.firebaseapp.com',
    storageBucket: 'ebook-c1668.appspot.com',
  );

}